application: melvinlim-1048
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /
  script: index.php
- url: /index\.html
  script: index.php
- url: /index\.php
  script: index.php
- url: /gardening.php
  script: gardening.php
- url: /electronics.php
  script: electronics.php
- url: /(.*\.html)
  static_files: static/\l
  upload: static/(.*\.html)
